name: Auto Release Library

on:
  push:
    tags:
      - 'v*' 

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Extract Latest Changelog
        id: extract_changelog
        run: |
          sed -n '/^## \[v/,/^## \[v/p' CHANGELOG.md | sed '$d' > latest_changes.txt

      - name: Create Arduino Library Zip
        
        run: zip -r Grobot_Animations.zip . -x ".git*" ".github*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Grobot_Animations.zip
          name: Release ${{ github.ref_name }}
          body_path: latest_changes.txt
          draft: false
          prerelease: false